### PR TITLE
First draft of an FAQ Page

### PR DESCRIPTION
**Pull request by Thiyaghessan**
Hi Jesse,

I drafted an FAQ page based on our thread in Issue #19 . Let me know if you'd like any edits, otherwise we can merge it into the site's main repository. 

Best,
Thiya

### CODE REVIEW

**Comment by lecy** [comment]
Do we need a QMD for the FAQ page? 

In general the goal is to use MD files because they are easy to edit and do not require compilation. The main exception on the site is data stories, which require RMarkdown (qmd) for obvious reasons. 

Whenever possible, though, we should use basic MD files to avoid the problem of duplicated files and additional dependencies. 

If it is a main page at the header level let's put the file in the main folder (repo base) with the other header files like "contacts.md" instead of creating additional folders.

**Comment by Thiyaghessan** [comment]
Could we not place the header file in the base repo, maintenance is easier when we don't have web pages intermixed with config .yml files. Each folder can then be documented accordingly so new maintainers know where to find files belonging to different sections of the web page.

**Comment by lecy** [comment]
It's standard practice to have header-level pages in the repo base. For example, index.html, about.md, contact.md, resources.html, datasets.html, etc. 

If it's a library of pages then a folder makes sense (catalogs, widgets, etc). For a single page like the FAQ.md at the top level I think it's more consistent in the main folder. 

Thoughts?

**Comment by Thiyaghessan** [comment]
Yes that works, I like that approach.

**Pull request merged**
